export enum EnvOptionName {
  BITGET_API_KEY = 'BITGET_API_KEY',
  BITGET_SECRET_KEY = 'BITGET_SECRET_KEY',
  BITGET_PASSPHRASE_PASSPHRASE = 'BITGET_PASSPHRASE_PASSPHRASE',
  BITGET_URL_BASE = 'BITGET_URL_BASE',
}
